
spring:
  application:
    name: service1
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://192.168.0.231:8052 
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.231:8050/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8061
server:
  port: 8061 #service1 占用8061
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 40000  # feign 超时控制
service0:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 500
    MaxAutoRetries: 1  # SR6版本,这里设为1,会重试3次,重试次数还和另外的两个值有关
 
 